apiVersion: v1
kind: Service
metadata:
  labels:
    app: department
  name: department
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: department
  type: ClusterIP