server:
  port: 8082

spring:
  application:
    name: department
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgresql-db:5432/myapp"
    username: postgres
    password: megazone00!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
eureka:
  client:
    enabled: false
