apiVersion: v1
kind: Service
metadata:
  name: {{ include "sck-sample.fullname" . }}-department
  labels:
    {{- include "sck-sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.department.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sck-sample.selectorLabels" . | nindent 4 }}-department
