server:
  port: 8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee
          predicates:
            - Path=/msa/employee/**
          uri: lb://employee
          filters:
            - RewritePath=/msa/employee/(?<segment>.*), /$\{segment}
        - id: department
          predicates:
            - Path=/msa/department/**
          uri: lb://department
          filters:
            - RewritePath=/msa/department/(?<segment>.*), /$\{segment}