name: Space-H

on:
  push:
    branches: [ "main" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Find change modules
        uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: true
          format: csv

      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }}

      - name: Execute Gradle build
        run: |
          for folder in $(echo ${{ steps.get_changed.outputs.changed }} | tr ',' '\n'); do
            echo "Building in $folder..."
            if [ -f "$folder/Dockerfile" ]; then
              echo "Building gradle in $folder..."
              (cd "$folder" && ./gradlew build &&  ls ./build/libs)
            fi
          done

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 077728726991.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker images
        run: |
          IFS=',' read -ra MODULES <<< "${{ steps.get_changed.outputs.changed }}"
          for module in "${MODULES[@]}"; do
            echo "Building Docker image in $module..."
            if [ -f "$module/Dockerfile" ]; then
              docker build -t 077728726991.dkr.ecr.us-east-2.amazonaws.com/$module "$module"
              docker push 077728726991.dkr.ecr.us-east-2.amazonaws.com/$module
            fi
          done